[package]
name = "bitbox-api"
authors = ["Marko Bencun <benma@bitbox.swiss>"]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "A library to interact with the BitBox02 hardware wallet"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
hidapi = { version = "2.3", optional = true }
prost = "0.11"
semver = "1.0.17"
noise-protocol = "0.1"
noise-rust-crypto = "0.5.0"
base32 = "0.4.0"
zeroize = "1"
async-trait = "0.1.68"
byteorder = "1.3.2"
thiserror = "1.0"
hex = { version = "0.4" }
bitcoin = { version = "0.30.0", optional = true, features = ["base64"] }

tokio = { version = "1", optional = true, features = ["time"] }
enum-assoc = { version = "1.1.0", optional = true }
gloo-utils = { version = "0.1.7", features = ["serde"], optional = true }
getrandom = { version = "0.2", features = ["js"], optional = true }
wasm-bindgen = { version = "0.2.63" }
wasm-bindgen-futures = { version ="0.4.37" }
js-sys = { version = "0.3.64", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
web-sys = { version = "0.3.64", features = ["Storage", "Window"], optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.13"
futures = { version = "0.3.28", default-features = false, features = ["executor"] }

[build-dependencies]
prost-build = { version = "0.11" }

[[example]]
name = "connect"
required-features = ["usb", "tokio/rt", "tokio/macros"]

[[example]]
name = "btc_signtx"
required-features = ["usb", "tokio/rt", "tokio/macros"]

[[example]]
name = "btc_sign_psbt"
required-features = ["usb", "tokio/rt", "tokio/macros", "bitcoin"]

[[example]]
name = "btc_miniscript"
required-features = ["usb", "tokio/rt", "tokio/macros", "bitcoin"]

[profile.release]
# Reduce wasm binary size.
opt-level = 'z'
codegen-units = 1
lto = true

[features]
usb = ["dep:hidapi"]
wasm = [
  "dep:enum-assoc",
  "dep:getrandom",
  "dep:js-sys",
  "serde",
  "dep:web-sys",
  "dep:gloo-utils",
]

serde = [
  "dep:serde",
  "dep:serde_json",
  "hex/serde",
]